/* classie */
!function(s){"use strict";function e(s){return new RegExp("(^|\\s+)"+s+"(\\s+|$)")}function n(s,e){var n=t(s,e)?c:a;n(s,e)}var t,a,c;"classList"in document.documentElement?(t=function(s,e){return s.classList.contains(e)},a=function(s,e){s.classList.add(e)},c=function(s,e){s.classList.remove(e)}):(t=function(s,n){return e(n).test(s.className)},a=function(s,e){t(s,e)||(s.className=s.className+" "+e)},c=function(s,n){s.className=s.className.replace(e(n)," ")});var o={hasClass:t,addClass:a,removeClass:c,toggleClass:n,has:t,add:a,remove:c,toggle:n};"function"==typeof define&&define.amd?define(o):"object"==typeof exports?module.exports=o:s.classie=o}(window);

/* Main.js */
!function(t){"use strict";function e(){n(),a()}function n(){for(var t=c(),e=0;m>e;++e){var n=v[e],a=t.indexOf(e);y!==e?(classie.add(n,"page--inactive"),-1!==a?(n.style.WebkitTransform="translate3d(0,100%,0)",n.style.transform="translate3d(0,100%,0)"):(n.style.WebkitTransform="translate3d(0,75%,-300px)",n.style.transform="translate3d(0,75%,-300px)")):classie.remove(n,"page--inactive"),n.style.zIndex=y>e?parseInt(y-e):parseInt(m+y-e),-1!==a?n.style.opacity=parseFloat(1-.1*a):n.style.opacity=0}}function a(){g.addEventListener("click",r),h.forEach(function(t){var e=t.getAttribute("href").slice(1);t.addEventListener("click",function(t){t.preventDefault(),o(e)})}),v.forEach(function(t){var e=t.getAttribute("id");t.addEventListener("click",function(t){b&&(t.preventDefault(),o(e))})}),document.addEventListener("keydown",function(t){if(b){var e=t.keyCode||t.which;27===e&&i()}})}function r(){b?i():(s(),b=!0)}function s(){classie.add(g,"menu-button--open"),classie.add(p,"pages-stack--open"),classie.add(k,"pages-nav--open");for(var t=c(),e=0,n=t.length;n>e;++e){var a=v[t[e]];a.style.WebkitTransform="translate3d(0, 75%, "+parseInt(-200-50*e)+"px)",a.style.transform="translate3d(0, 75%, "+parseInt(-200-50*e)+"px)"}}function i(){o()}function o(t){var e=t?document.getElementById(t):v[y],a=v.indexOf(e),r=c(a);e.style.WebkitTransform="translate3d(0, 0, 0)",e.style.transform="translate3d(0, 0, 0)",e.style.opacity=1;for(var s=0,i=r.length;i>s;++s){var o=v[r[s]];o.style.WebkitTransform="translate3d(0,100%,0)",o.style.transform="translate3d(0,100%,0)"}t&&(y=a),classie.remove(g,"menu-button--open"),classie.remove(k,"pages-nav--open"),f(e,function(){classie.remove(p,"pages-stack--open"),n(),b=!1})}function c(t){var e=m>y+1?y+1:0,n=m>y+2?y+2:1,a=[];return t!=y&&a.push(y),t!=e&&a.push(e),t!=n&&a.push(n),a}var l={transitions:Modernizr.csstransitions},d={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",msTransition:"MSTransitionEnd",transition:"transitionend"},u=d[Modernizr.prefixed("transition")],f=function(t,e){var n=function(t){if(l.transitions){if(t.target!=this)return;this.removeEventListener(u,n)}e&&"function"==typeof e&&e.call(this)};l.transitions?t.addEventListener(u,n):n()},p=document.querySelector(".pages-stack"),v=[].slice.call(p.children),m=v.length,y=0,g=document.querySelector("button.menu-button"),k=document.querySelector(".pages-nav"),h=[].slice.call(k.querySelectorAll(".link--page")),b=!1;e()}(window);

/* Form.js */
!function(t){
	"use strict";

	function e(t,e){for(var s in e)e.hasOwnProperty(s)&&(t[s]=e[s]);return t}
	function s(t,s){this.el=t,this.options=e({},this.options),e(this.options,s),this._init()}

	var i={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",msTransition:"MSTransitionEnd",transition:"transitionend"},
		n=i[Modernizr.prefixed("transition")],
		r={transitions:Modernizr.csstransitions};

	s.prototype.options={onSubmit:function(){return!1}},
	s.prototype._init=function(){this.current=0,this.questions=[].slice.call(this.el.querySelectorAll("ol.questions > li")),this.questionsCount=this.questions.length,classie.addClass(this.questions[0],"current"),this.ctrlNext=this.el.querySelector("button.next"),this.progress=this.el.querySelector("div.progress"),this.questionStatus=this.el.querySelector("span.number"),this.currentNum=this.questionStatus.querySelector("span.number-current"),this.currentNum.innerHTML=Number(this.current+1),this.totalQuestionNum=this.questionStatus.querySelector("span.number-total"),this.totalQuestionNum.innerHTML=this.questionsCount,this.error=this.el.querySelector("span.error-message"),this._initEvents()},
	s.prototype._initEvents=function(){var t=this,e=this.questions[this.current].querySelector("input"),s=function(){e.removeEventListener("focus",s),classie.addClass(t.ctrlNext,"show")};e.addEventListener("focus",s),this.ctrlNext.addEventListener("click",function(e){e.preventDefault(),t._nextQuestion()}),document.addEventListener("keydown",function(e){var s=e.keyCode||e.which;13===s&&(e.preventDefault(),t._nextQuestion())}),this.el.addEventListener("keydown",function(t){var e=t.keyCode||t.which;9===e&&t.preventDefault()})},
	s.prototype._nextQuestion=function(){if(!this._validade())return!1;this.current===this.questionsCount-1&&(this.isFilled=!0),this._clearError();var t=this.questions[this.current];if(++this.current,this._progress(),!this.isFilled){this._updateQuestionNumber(),classie.addClass(this.el,"show-next");var e=this.questions[this.current];classie.removeClass(t,"current"),classie.addClass(e,"current")}var s=this,i=function(t){r.transitions&&this.removeEventListener(n,i),s.isFilled?s._submit():(classie.removeClass(s.el,"show-next"),s.currentNum.innerHTML=s.nextQuestionNum.innerHTML,s.questionStatus.removeChild(s.nextQuestionNum),e.querySelector("input").focus())};r.transitions?this.progress.addEventListener(n,i):i()},
	s.prototype._progress=function(){this.progress.style.width=this.current*(100/this.questionsCount)+"%"},
	s.prototype._updateQuestionNumber=function(){this.nextQuestionNum=document.createElement("span"),this.nextQuestionNum.className="number-next",this.nextQuestionNum.innerHTML=Number(this.current+1),this.questionStatus.appendChild(this.nextQuestionNum)},
	s.prototype._submit=function(){this.options.onSubmit(this.el)},
	s.prototype._validade=function(){var t=this.questions[this.current].querySelector("input").value;return""===t?(this._showError("EMPTYSTR"),!1):!0},
	s.prototype._showError=function(t){var e="";switch(t){case"EMPTYSTR":e="Veuillez remplir le formulaire avant de continuer";break;}this.error.innerHTML=e,classie.addClass(this.error,"show")},
	s.prototype._clearError=function(){classie.removeClass(this.error,"show")},

	t.stepsForm=s;
}(window);

/* konami */
!function(t){"user strict";konami_code="38,38,40,40,37,39,37,39,66,65";key_stack=new Array();window.onkeydown=function(e){console.log(e);console.log(e.keyCode);key_stack.push(e.keyCode);if(key_stack.join().substring(key_stack.join().length-konami_code.length)==konami_code){shake_js=document.createElement("script");shake_js.type="text/javascript";shake_js.async=true;/*shake_js.src=("https:"==document.location.protocol ? "https://":"http://")+"gist.githubusercontent.com/devn/5007287/raw/57f8c09fc9dbbdb733952e1117bf33db1cf9a3d2/harlem-shake.js";*/shake_js.src="js/harlem-shake.js";document.getElementsByTagName("head")[0].appendChild(shake_js);setTimeout(function(){document.getElementsByTagName("head")[0].removeChild(shake_js);},35000);}}}(window);